### PR TITLE
Update Gradle and default Jenkins version

### PR DESCRIPTION
**Pull request by bugfest**
This PR upgrades gradle and default jenkins version:
- Current gradle version is not compatible with `Java 18` (Upgrading to `7.5.1` as per https://docs.gradle.org/current/userguide/compatibility.html fixes the issue)
- Current default Jenkins is outdated. Latest version is `2.346.3`

### CODE REVIEW

**Comment by nre-ableton** [comment]
Hi @bugfest, thanks for your PR! There are two things that need to be done before we can merge it:

1. Can you please sign our CLA? https://ableton.github.io/cla/ Alternately, if you really don't want to sign the CLA, I can recreate this PR myself, but you won't be credited in the git history etc.
2. Can you please add a commit to bump the `VERSION` file? Bumping the patch version should be enough (ie, to version `0.1.23`). This will trigger a new release to be published on Ansible Galaxy when this PR is merged.

Thanks!

**Comment by nre-ableton** [comment]
@ablbot runci

**Comment by bugfest** [comment]
Hi @nre-ableton, Thanks your your quick review. CLA is signed now. Gonna bump that version file, give me a sec

**Comment by bugfest** [comment]
> Hi @bugfest, thanks for your PR! There are two things that need to be done before we can merge it:
> 
>     1. Can you please sign our CLA? https://ableton.github.io/cla/ Alternately, if you really don't want to sign the CLA, I can recreate this PR myself, but you won't be credited in the git history etc.
> 
>     2. Can you please add a commit to bump the `VERSION` file? Bumping the patch version should be enough (ie, to version `0.1.23`). This will trigger a new release to be published on Ansible Galaxy when this PR is merged.
> 
> 
> Thanks!

(1) & (2) tasks done : )

**Comment by nre-ableton** [comment]
Hi @bugfest, the code changes look fine but the CLA is not exactly very specific. :smile: Our legal team is currently reviewing it to see if we can merge this PR in spite of that.

**Comment by nre-ableton** [comment]
Hi @Bugfest,
Sorry about the delay. I have heard back from our legal team, and unfortunately, we are not able to accept this CLA because it needs to have a legal name and address.

However, I have confirmed with our legal team that all personal data we receive in CLAs is protected under our [privacy policy](https://www.ableton.com/en/privacy/) and hence the GDPR (since Ableton is based in Berlin, Germany). In other words, this data is not given to third-parties, nor is it used for marketing or any other purposes other than allow us to merge GitHub PRs.

This is not explicitly stated in the CLA because the privacy policy covers Ableton's "users", which includes people that sign CLAs (since they have entered a legal agreement with the company, similar to users of our software). However, after these discussions, our legal team will update the CLA to make the privacy aspect explicit.

I'm sorry to be a bother, but could you please re-sign the CLA?

If you don't want to sign the CLA, then we can prepare a PR to the Jenkins/Gradle versions, since this is something quite trivial and something we'd normally do. However, your [other PR](https://github.com/Ableton/ansible-role-jenkins-jcasc/pull/211/files) would unfortunately be harder for us to accept.

**Comment by bugfest** [comment]
Hi @nre-ableton, thanks for the information; it indeed aliviated my privacy concerns. You should have a new CLA in place already - hope it unblocks both (and future!) PRs

**Comment by nre-ableton** [comment]
@bugfest I just saw the new CLA, thank you very much for this. :+1:

Now, let's get back to business. The PR looks fine, it just needs to be rebased and fix the conflict with the `VERSION` file. I'll take care of this myself, sorry for the force-push.

**Comment by nre-ableton** [comment]
Bah, the CI error is again the fault of our Jenkins instance, not being able to build external PR branches. However, I just built these commands with my own branch and they are fine.

**Comment by bugfest** [comment]
Thanks @nre-ableton !

**Pull request merged**
