### PR TITLE
Allow customized Jenkins URL prefix

### PR DESCRIPTION
**Pull request by bugfest**
This PR adds a new variable `jenkins_prefix` that allows to set a custom URL prefix

### CODE REVIEW

**Comment by nre-ableton** [comment]
Hi @bugfest, thanks for the PR. I will review this once we sort out the issues with the CLA and merge #209.

**Comment by bugfest** [comment]
Thanks @nre-ableton - looking forward to it

**Review by nre-ableton — COMMENTED** [review]
Generally speaking, this PR looks good to me. :+1: For now, I just have one suggestion/question regarding documentation of `jenkins_prefix`.

But beyond that, there should also be a test included to make sure that the prefix behaves as intended. However, I'll take care of that and push a fixup to your branch.

**Comment by nre-ableton** [comment]
So, I pushed a WIP commit that adds a `jenkins_prefix` to the Molecule test cases, as well as fixing two other `url` instances that I found. Unfortunately, the molecule tests fail when trying to add/verify users. I will investigate this more tomorrow. :detective:

**Comment by bugfest** [comment]
Hi @nre-ableton, thanks for your comments. All good points. I'll be fixing them and update this PR

**Comment by nre-ableton** [comment]
> Hi @nre-ableton, thanks for your comments. All good points. I'll be fixing them and update this PR

Sounds good, but don't worry about my WIP commit for the molecule tests. I'll look at that today.

**Comment by bugfest** [comment]
Hi @nre-ableton, I've conducted some tests (some of them with interesting results):

Note: I've used `jenkins-2.346.3` for these tests. 

| Prefix value  | Jenkins Start | Service URL                        |
|---------------|:-------------:|------------------------------------|
| <empty> or "" |      Yes      | http://localhost:8080/             |
| /             |      Yes      | http://localhost:8080/             |
| //            |      Yes      | http://localhost:8080/             |
| ///           |      Yes      | http://localhost:8080/             |
| .             |      Yes      | Error: Infinite redirection loop   |
| ..            |      Yes      | Error: Not found                   |
| ...           |      Yes      | Error: Not found                   |
| /.            |      Yes      | Error: Not found                   |
| /..           |      Yes      | Error: Not found                   |
| /...          |      Yes      | http://localhost:8080/.../         |
| * (literal)   |      Yes      | Error: Redirect to /* & Not found  |
| abc           |      Yes      | Error: Not found                   |
| ./abc         |      Yes      | Error: Not found                   |
| ./abc         |      Yes      | Error: Not found                   |
| ../abc        |      Yes      | Error: Not found                   |
| .../abc       |      Yes      | Error: Not found                   |
| /abc          |      Yes      | http://localhost:8080/abc/         |
| //abc         |      Yes      | http://localhost:8080//abc/        |
| ///abc        |      Yes      | http://localhost:8080///abc/       |
| /abc/         |      Yes      | http://localhost:8080/abc/         |
| /abc/def      |      Yes      | http://localhost:8080/abc/def/     |
| /abc//def     |      Yes      | http://localhost:8080/abc//def/    |
| /abc/./def    |      Yes      | Error: Not found                   |
| /abc/../def   |      Yes      | Error: Not found                   |
| /abc/.../def  |      Yes      | http://localhost:8080/abc/.../def/ |
| /./abc        |      Yes      | Error: Not found                   |
| /../abc       |      Yes      | Error: Not found                   |
| /.../abc      |      Yes      | http://localhost:8080/.../abc/     |

Conclusions:
- Jetty requires the prefix to be empty or start with "/" to properly route the URI
- Multiple slashes characters are stripped by Jetty only at the beginning of the prefix
- Single and double dot (".") are interpreted as relative path but Jetty does handle them properly
- When using 3 or more dots as part of the URI, prefix is properly routed
- '*' character is also interpreted by Jetty, leading to unknown results.

I think the safest is to set prefix="/" and add an assert to enforce it starting with "/".
That should avoid known not-working scenarios. What do you think?

**Comment by nre-ableton** [comment]
@bugfest Thanks, it's looking much better. I will probably rebase, squash, and force-push this branch soon, just FYI.

**Review by nre-ableton — APPROVED** [review]
@bugfest Ok, I have finished making my changes, which include:

- Minor cleanups to the git commit message and the documentation of `jenkins_prefix`
- Adding a molecule test case for this
- Collapsing unnecessary multi-line YAML statements thanks to the removal of the `regexp_replace` filter
- Confirming that this change passes CI (it does)

Can you please take a quick look? If you're ok with my changes, I'll go ahead and merge the PR.

**Comment by bugfest** [comment]
> Can you please take a quick look? If you're ok with my changes, I'll go ahead and merge the PR.

Thanks @nre-ableton - Looks good. Ready to rock!

**Comment by nre-ableton** [comment]
@bugfest Great, thanks! A new version should be published by our CI servers in a few minutes. Thanks again for your contribution! :+1:

**Pull request merged**
